-- MySQL dump 10.13  Distrib 8.0.41, for Linux (x86_64)
--
-- Host: localhost    Database: automotive
-- ------------------------------------------------------
-- Server version	8.0.41-0ubuntu0.24.04.1

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `angletag_predicts`
--

DROP TABLE IF EXISTS `angletag_predicts`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `angletag_predicts` (
  `image_id` int NOT NULL,
  `model_label` varchar(32) DEFAULT NULL,
  `model_score` float DEFAULT NULL,
  PRIMARY KEY (`image_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `angletags`
--

DROP TABLE IF EXISTS `angletags`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `angletags` (
  `image_id` int NOT NULL,
  `angle` varchar(32) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `manual_annotation` tinyint DEFAULT NULL,
  `pk` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`pk`),
  KEY `idx_angle` (`angle`),
  KEY `idx_manual_annotation` (`manual_annotation`)
) ENGINE=InnoDB AUTO_INCREMENT=20006 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `bintag_predicts`
--

DROP TABLE IF EXISTS `bintag_predicts`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `bintag_predicts` (
  `image_id` int NOT NULL,
  `model1_results` float DEFAULT NULL,
  `model2_results` float DEFAULT NULL,
  `model3_results` float DEFAULT NULL,
  `model4_results` float DEFAULT NULL,
  PRIMARY KEY (`image_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `images`
--

DROP TABLE IF EXISTS `images`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `images` (
  `id` int NOT NULL AUTO_INCREMENT,
  `listing_id` int NOT NULL,
  `processed` tinyint NOT NULL DEFAULT '0',
  `use_image` tinyint DEFAULT NULL,
  `certainty_of_outside_yolo` int DEFAULT NULL,
  `yolobox_top_left_x` int DEFAULT NULL,
  `yolobox_top_left_y` int DEFAULT NULL,
  `yolobox_bottom_right_x` int DEFAULT NULL,
  `yolobox_bottom_right_y` int DEFAULT NULL,
  `area` float DEFAULT NULL COMMENT 'surface area of bounding box in percentage between 0 and 1',
  `confidence` float DEFAULT NULL COMMENT 'confidence score of YOLO in percentage between 0 and 1',
  `image_path` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  PRIMARY KEY (`id`,`listing_id`),
  KEY `idx_imagelisting` (`listing_id`)
) ENGINE=InnoDB AUTO_INCREMENT=16307536 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `listings`
--

DROP TABLE IF EXISTS `listings`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `listings` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `autoscout_id` varchar(128) NOT NULL COMMENT 'UUIDV4 generated by Autoscout',
  `brand` varchar(255) DEFAULT NULL COMMENT 'brand as extracted from Autodoc',
  `model` varchar(255) DEFAULT NULL COMMENT 'Model as extracted from Autoscout (aggregated filed content)',
  `year` int DEFAULT NULL COMMENT 'iterator between earliest and latest occurences of the model',
  `first_registration` varchar(255) DEFAULT NULL COMMENT 'actual first registration date of the listing',
  `make_name_autoscout` varchar(255) DEFAULT NULL COMMENT 'Brand name as listed on AUtoscout',
  `model_name_autoscout` varchar(255) DEFAULT NULL COMMENT 'MOdel name as listed on autoscout',
  `price` int DEFAULT NULL COMMENT 'Price as listed on autoscout',
  `mileage` int DEFAULT NULL COMMENT 'Mileage as listed on autoscout (in KM)',
  `make_id` int DEFAULT NULL COMMENT 'make id as listed in autouscout',
  `model_id` int DEFAULT NULL COMMENT 'model id as listed in autoscout (part of the JSON taxonomy)',
  `variant_id` int DEFAULT NULL COMMENT 'variant id as listed in autoscout (part of JSON taxonomy)',
  `generation_id` int DEFAULT NULL COMMENT 'generation id a listed in autoscout (part of JSON taxonomy)',
  `motortype_id` int DEFAULT NULL COMMENT 'Motortype id as listed on autoscout (part of JSON taxonomy',
  `trim_id` int DEFAULT NULL COMMENT 'trim id as listed on autoscout (part of JSON taxonomy)',
  `shelltype` varchar(64) DEFAULT NULL,
  `doorcount` int DEFAULT NULL,
  `weight` int DEFAULT NULL,
  `normlabel` varchar(100) DEFAULT NULL,
  `countrycode` varchar(8) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_countrycode` (`countrycode`)
) ENGINE=InnoDB AUTO_INCREMENT=857517 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `models`
--

DROP TABLE IF EXISTS `models`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `models` (
  `model_id` int NOT NULL AUTO_INCREMENT COMMENT 'Primary key of the model',
  `brand` varchar(100) DEFAULT NULL,
  `modelname` varchar(100) DEFAULT NULL,
  `bodystyle` varchar(100) DEFAULT NULL,
  `chassiscode` varchar(32) DEFAULT NULL,
  `introduction_date` date DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  PRIMARY KEY (`model_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Overview of car models with chassis codes required for uniquely identifying a car. BRAND name is not normalized in this db.';
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `tracker`
--

DROP TABLE IF EXISTS `tracker`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `tracker` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `make` varchar(255) DEFAULT NULL,
  `model` varchar(255) DEFAULT NULL,
  `year` int DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2025-05-01 17:57:44
